# Generated by Django 2.2.4 on 2019-08-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
        ),
    ]
