# Generated by Django 2.2.4 on 2019-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190822_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.Avaliacao'),
        ),
    ]
