# Generated by Django 2.2.4 on 2019-08-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190822_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='aprovado',
            field=models.BooleanField(null=True),
        ),
    ]
