# Generated by Django 2.2.4 on 2019-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190822_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
